name: Build and Deploy to GitHub Pages

on: 
  push:
    branches:
      - '**'
      - 'main'  #! to Exclude main branch

jobs:
  build:
    name: Bundle and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure write access for deployment

    strategy:
      matrix:
        node-version: [20.x] 

    steps:
      # 1️⃣ Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4.1.2

      # 2️⃣ Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      # 3️⃣ Extract the branch name
      - name: Extract Branch Name
        id: extract_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      # 4️⃣ Checkout existing `gh-pages` branch (if exists)
      - name: Checkout Existing Bundles
        uses: actions/checkout@v4.1.2
        continue-on-error: true
        with:
          ref: gh-pages
          path: bundles

      # 5️⃣ Install dependencies
      - name: Install Dependencies
        run: npm install

      # 6️⃣ Build the project and place it inside `bundles/{branch-name}`
      - name: Build Project
        run: npm run bundle -- --folder=bundles/${{ env.branch }}

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: bundles
